### ISSUE TITLE
Any chance of updating for current Swift?

### ISSUE THREAD

**Issue by WadeSellers** [VojtaStavik/VSTextField#1]
Love this simple drop-in but since we've moved from 1.2 to I think 2.1 now, there's a bunch of errors and I'm not completely sure how to solve them all.

**Comment by technoY2K** [comment]
I just did a pull request, so hopefully they accept soon. If not you can pull my version down. I'll check back

**Comment by VojtaStavik** [comment]
Hey @WadeSellers and @jhamPac, thanks for the PR. Great work! I will merge it ASAP.

**Comment by VojtaStavik** [comment]
Closed by https://github.com/VojtaStavik/VSTextField/pull/2
