### ISSUE TITLE
Swift 3.2 iOS 11 Problem

### ISSUE THREAD

**Issue by EmersonCarpes** [VojtaStavik/VSTextField#11]
I'm testing VSTextField with Swift 3.2 on iOS 11 and when I use .text to change value it enter in a eternal loop running running textDidChange() forever. Any idea what it might be?

**Comment by VojtaStavik** [comment]
@EmersonCarpes  Thank you for reporting the bug. I've pushed the fix. Could you confirm the fix helps?

**Comment by EmersonCarpes** [comment]
Sorry for delay, the problem continues and occurs when I use setFormatting

**Comment by VojtaStavik** [comment]
@EmersonCarpes  I think I fixed it. Could you please verify it's OK now?

**Comment by EmersonCarpes** [comment]
It's working now. Thank you!
