### ISSUE TITLE
String get disappear when use in UITableview.

### ISSUE THREAD

**Issue by Premal-Khetani** [VojtaStavik/VSTextField#12]
Hello @VojtaStavik ,
This is great category for UITextField. 
I am getting issue as below. 
I used textfield in UITableviewCell. Now when i reload table view i set already existing string to textfield. that time for ex. Actual string "123-456-7891" will be shown as "123-456-78". The last two character were disappeared. 

What i do is i update text field and reload data of table view in textFieldDidEndEditing method.

The issue appears at that time

Kindly let me know what to do. 

Thank you

**Comment by VojtaStavik** [comment]
Hey @Premal-Khetani . It's would be great if you could share a code snippet or example project of what exactly are you doing.

**Comment by Premal-Khetani** [comment]
i used UITextField in UITableviewCell.

Step 1 : Add value to textfield. 
Step 2 : update value by textFieldDidEndEditing method
Step 3 : now reload cell or tableview

here the last two digits were disappeared. 

hope this can clear the scenario.

**Comment by vst-ableton** [comment]
@Premal-Khetani When you reload the table view I suppose you store the value from the text field somewhere and then put it back again? Can you share a code snippet?

**Comment by VojtaStavik** [comment]
@Premal-Khetani When you reload the table view I suppose you store the value from the text field somewhere and then put it back again? Can you share a code snippet?

**Comment by VojtaStavik** [comment]
Closing this one because of the lack of information.
