### ISSUE TITLE
Swift 4.0 iOS 11 Warning Issue - substring function is deprecated

### ISSUE THREAD

**Issue by johansalazarcuellar** [VojtaStavik/VSTextField#14]
Hello, good morning, I'm trying VSTextField Swift 4.0 IOS 11 and when I use it is working, but xcode is showing some warnings that say 'substring(with:)' is deprecated: use string slice subscript.' in several lines of the file VSTextField.swift 

I was wondering if it is possible is to realize this function for swift 4, thank you update, this tool is great. I await your prompt response

**Comment by vst-ableton** [comment]
Hey! Thank you for opening this issue. Feel free to submit a PR if you have a fix ready.

**Comment by munirwanis** [comment]
Hey, I made a PR. Can someone look at it?

**Comment by VojtaStavik** [comment]
Closed by https://github.com/VojtaStavik/VSTextField/pull/16

**Comment by VojtaStavik** [comment]
Closed by https://github.com/VojtaStavik/VSTextField/pull/16

**Comment by munirwanis** [comment]
Thank you @VojtaStavik !
