### ISSUE TITLE
Setup Travis to run tests on every PR

### ISSUE THREAD

**Issue by VojtaStavik** [VojtaStavik/VSTextField#19]
After we merge #15, it would be great to setup Travis support for this repo, so we have all the new PRs automatically tested.

**Comment by munirwanis** [comment]
@VojtaStavik Do you think Travis is the best option? I was thinking about bitrise.

**Comment by VojtaStavik** [comment]
@munirwanis I have no experience with bitrise. Do you use it? Why do you think it's a better choice?

**Comment by munirwanis** [comment]
@VojtaStavik I use it. I think it's better just because it's more UI friendly, you can setup everything through the dashboard instead of doing `.yml` files. And Bitrise is focused only on mobile the rest is very equal to Travis.

**Comment by VojtaStavik** [comment]
OK, let's try it out! 🎉

**Comment by munirwanis** [comment]
I had some time yesterday and started working on this issue and on #18 as well! Hope to finish this on weekend!

**Comment by munirwanis** [comment]
@VojtaStavik 

I can't add the repo to Bitrise beacause I don't have admin rights.

![screen shot 2018-02-12 at 13 47 43](https://user-images.githubusercontent.com/8562684/36105327-7b72d506-0ffb-11e8-9f43-a5ac5e6aeac1.png)

Can you add it for me and gimme privileges (user: `munirwanis`) on bitrise so I can continue the automation process?

- On validation setup choose branch __feature/bitrise__
- On project build configuration choose __fastlane__ e select lane __test__

Thanks.

**Comment by VojtaStavik** [comment]
Thank you for working on this @munirwanis 👍  I added the repo as you requested. I also invited you to the team on Bitrise and granted you admin privileges. Let me know if you need anything else.
