### ISSUE TITLE
Editing Changed event fired before text changes

### ISSUE THREAD

**Issue by drakmail** [VojtaStavik/VSTextField#4]
`Editing Changed` event fired before text changes, so I have in `sender.text` all characters except last =/

**Comment by VojtaStavik** [comment]
Can you be more specific? What are the steps to simulate it?

**Comment by VojtaStavik** [comment]
I'm going to close this since there's no more info about the issue from you.

**Comment by RodolfoAntonici** [comment]
I had the same problem, here how it happens

This is a common approach to take the text when the TextField change it's value:
`self.textField.addTarget(self, action: #selector(textFieldDidChangeValue(_:)), forControlEvents: .EditingChanged)`

```
func textFieldDidChangeValue(textField: UITextField) {

        print(textField.text)

    }
```

It loses the last character. Reading your code, here's why:

```
override var text: String! {
        set {
            super.text = newValue
            textDidChange() // format string properly even when it's set programatically
        }

        get {
            return formatting == .NoFormatting ? super.text : finalStringWithoutFormatting
        }
    }
```

When you override the super.text = newValue, it calls the EditingChanged.
How to solve? Well... I didn't figure it out a workaround yet.
I used a delegate to wrap things up. (easy/no-time solution)
