### ISSUE TITLE
Control event EditingChanged doesn't work.

### ISSUE THREAD

**Issue by RodolfoAntonici** [VojtaStavik/VSTextField#6]
I had this problem, here how it happens

This is a common approach to take the text when the TextField change it's value:
`self.textField.addTarget(self, action: #selector(textFieldDidChangeValue(_:)), forControlEvents: .EditingChanged)`

```
func textFieldDidChangeValue(textField: UITextField) {

        print(textField.text)

    }
```

It loses the last character. Reading your code, here's why:

```
override var text: String! {
        set {
            super.text = newValue
            textDidChange() // format string properly even when it's set programatically
        }

        get {
            return formatting == .NoFormatting ? super.text : finalStringWithoutFormatting
        }
    }
```

When you override the super.text = newValue, it calls the EditingChanged.
How to solve? Well... I didn't figure it out a workaround yet.
I used a delegate to wrap things up. (easy/no-time solution)

**Comment by VojtaStavik** [comment]
Thank you very much for such a great report! I just pushed a fix for this issue. Could you please try it out and confirm that everything works as expected?
